# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: mypool

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    pool:
      name: mypool
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js 12.x'

      - script: |
          npm install -g @angular/cli@11.2.2
          npm install
          ng build --prod
        displayName: 'npm install and build'
        workingDirectory: '$(Build.SourcesDirectory)'


      - task: PublishBuildArtifacts@1
        inputs:
          #PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          PathtoPublish: dist
          ArtifactName: 'angular-artifact'
